import {
  Activity,
  AppWindow,
  Bot,
  ChartNoAxesCombined,
  Box,
  BriefcaseBusiness,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleOff,
  CirclePlay,
  CircleStop,
  CircleUserRound,
  Cloud,
  CloudOff,
  Contrast,
  CloudUpload,
  Code2,
  Copy,
  Cpu,
  FileUp,
  FolderTree,
  Gauge,
  Gavel,
  GitBranch,
  Grid2X2,
  HandHeart,
  HelpCircle,
  Image,
  Info,
  Lightbulb,
  KeyRound,
  Languages,
  Layers3,
  Link2Off,
  ListChecks,
  LockKeyhole,
  LogOut,
  Menu,
  Monitor,
  Network,
  Paperclip,
  PiggyBank,
  Pencil,
  PlayCircle,
  Play,
  PlugZap,
  Power,
  RefreshCw,
  Rocket,
  Route,
  Save,
  ScanSearch,
  ScrollText,
  Search,
  SearchX,
  Server,
  Shield,
  ShieldCheck,
  ShieldOff,
  Signal,
  Sparkles,
  SquareTerminal,
  Star,
  Sun,
  Terminal,
  TriangleAlert,
  ToggleLeft,
  ToggleRight,
  Upload,
  UserRound,
  Wifi,
  Eye,
  Download,
  Moon,
  FlaskConical,
  PauseCircle,
  Radio,
  RotateCcw,
  Settings,
  ToyBrick,
  Wrench,
  X,
  XCircle,
  Zap,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ExternalLink,
  Plus,
  Trash2,
} from "lucide-react";

const ICONS = {
  account_circle: CircleUserRound, account_tree: FolderTree, add: Plus, api: PlugZap,
  arrow_back: ArrowLeft, arrow_downward: ArrowDown, arrow_forward: ArrowRight, arrow_upward: ArrowUp,
  apps: AppWindow, attach_file: Paperclip, block: CircleOff, bolt: Zap, business: BriefcaseBusiness,
  cancel: XCircle, chat: Bot, check: Check, check_circle: CheckCircle2, checklist: ListChecks,
  chevron_left: ChevronLeft, chevron_right: ChevronRight, close: X, cloud: Cloud, cloud_upload: CloudUpload,
  bar_chart: ChartNoAxesCombined, cloud_off: CloudOff, code: Code2, computer: Monitor, content_copy: Copy, contrast: Contrast, dark_mode: Moon, data_object: Box, data_usage: Gauge, delete: Trash2, dns: Server, download: Download, edit: Pencil,
  error: XCircle, expand_more: ChevronDown, expand_less: ChevronUp, extension: Wrench, file_upload: FileUp,
  gavel: Gavel, grid_view: Grid2X2, help: HelpCircle, hourglass_top: Activity, hub: Network, image: Image, info: Info, key: KeyRound,
  keyboard_arrow_down: ChevronDown, keyboard_arrow_up: ChevronUp, lan: Network, language: Languages,
  layers: Layers3, light_mode: Sun, link_off: Link2Off, lock: LockKeyhole, lock_open: ShieldOff, logout: LogOut, menu: Menu, monitoring: Gauge,
  open_in_new: ExternalLink, pause_circle: PauseCircle, play_arrow: Play, play_circle: PlayCircle, power_off: Power, power_settings_new: Power,
  progress_activity: RefreshCw, psychology: Sparkles, radio_button_unchecked: Radio, refresh: RefreshCw, restart_alt: RotateCcw, restore: RefreshCw, rocket_launch: Rocket,
  route: Route, save: Save, savings: PiggyBank, schedule: Activity, science: FlaskConical, search: Search, search_off: SearchX, security: Shield, settings: Settings, shield: Shield, shield_lock: ShieldCheck, smart_toy: ToyBrick,
  star: Star, stop: CircleStop, stop_circle: CircleStop, sync_alt: ArrowRight, terminal: Terminal, terminal_log: ScrollText,
  toggle_off: ToggleLeft, toggle_on: ToggleRight, verified: ShieldCheck, verified_user: ShieldCheck, visibility: Eye, visibility_off: Eye, volunteer_activism: HandHeart, vpn_key: KeyRound, warning: TriangleAlert, wifi: Wifi,
};

export default function Icon({ name, className, ...props }) {
  const Component = ICONS[name] || ScanSearch;
  return <Component aria-hidden="true" className={className} {...props} />;
}
